package main

import (
	"fmt"
	"os"
	"strings"
)

// writeSemanticReport renders the E5 go/no-go markdown: methodology, pass@3
// OFF vs ON, a per-query table, latency (incl. the isolated embed cost), and a
// data-driven recommendation against the gate.
func writeSemanticReport(out string, sf semanticBenchFile, results []semResult) error {
	var b strings.Builder
	writeSemanticHeader(&b, sf)
	writeSemanticPassTable(&b, results)
	writeSemanticQueryTable(&b, results)
	writeSemanticLatency(&b, results)
	writeSemanticRecommendation(&b, results)
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil { //nolint:gosec,mnd // report is non-secret, world-readable by design
		return fmt.Errorf("writing semantic report %s: %w", out, err)
	}
	return nil
}

func writeSemanticHeader(b *strings.Builder, sf semanticBenchFile) {
	b.WriteString("# Semantic recall — go/no-go bench (E5, ADR-0006)\n\n")
	fmt.Fprintf(b, "Generated by `bench-runner -semantic` against the local Postgres, %d hand-labeled "+
		"NL/vibe queries from `bench/semantic-cluster.json`. Both arms run the **same** pipeline "+
		"(intent ON, identical ranker); the only difference is `LEMON_FF_SEMANTIC` — the OFF arm is "+
		"purely lexical, the ON arm embeds the query (all-MiniLM via Ollama) and adds the pgvector "+
		"recall channel. So the delta isolates the **marginal lift of the vector channel** over the "+
		"production lexical+intent baseline.\n\n", len(sf.Tests))
	b.WriteString("Ground truth is category/subcategory level (a vibe query should surface the right " +
		"*type* of business): a query passes if any top-3 result's category/subcategory contains an " +
		"expected token.\n\n")
}

func writeSemanticPassTable(b *strings.Builder, results []semResult) {
	offN, onN, gained, regressed, total := tallySemantic(results)
	b.WriteString("## pass@3\n\n")
	b.WriteString("| arm | pass@3 |\n|---|---|\n")
	fmt.Fprintf(b, "| semantic OFF (lexical+intent) | %d/%d (%.0f%%) |\n", offN, total, pct(offN, total))
	fmt.Fprintf(b, "| semantic ON (+ vector recall) | %d/%d (%.0f%%) |\n\n", onN, total, pct(onN, total))
	fmt.Fprintf(b, "**+%d gained** (lexical miss → semantic hit), **%d regressed**.\n\n", gained, regressed)
}

func writeSemanticQueryTable(b *strings.Builder, results []semResult) {
	b.WriteString("## per-query\n\n")
	b.WriteString("| query | off | on | on top-1 |\n|---|:--:|:--:|---|\n")
	for _, r := range results {
		if r.err != nil {
			fmt.Fprintf(b, "| %s | — | — | ERROR: %v |\n", r.q, r.err)
			continue
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", r.q, mark(r.offPass), mark(r.onPass), r.onTop1)
	}
	b.WriteString("\n")
}

func writeSemanticLatency(b *strings.Builder, results []semResult) {
	off, on, embed := latencies(results)
	b.WriteString("## latency (retrieve + rerank, local DB)\n\n")
	b.WriteString("| arm | p50 | p95 |\n|---|---|---|\n")
	fmt.Fprintf(b, "| semantic OFF | %dms | %dms |\n", percentile(off, pctl50), percentile(off, pctl95))
	fmt.Fprintf(b, "| semantic ON | %dms | %dms |\n", percentile(on, pctl50), percentile(on, pctl95))
	fmt.Fprintf(b, "| └ query-embed only | %dms | %dms |\n\n", percentile(embed, pctl50), percentile(embed, pctl95))
	b.WriteString("_Local engine time only; the deployed path adds ~30-40ms of network " +
		"(browser→Vercel→Fly→Supabase) toward the 100ms end-to-end p95 gate._\n\n")
}

func writeSemanticRecommendation(b *strings.Builder, results []semResult) {
	offN, onN, _, regressed, total := tallySemantic(results)
	_, on, _ := latencies(results)
	onP95 := percentile(on, pctl95)
	liftPP := pct(onN, total) - pct(offN, total) // percentage points

	liftOK := liftPP >= materialLiftPP
	latencyOK := onP95 <= engineP95Budget
	verdict := "GO"
	if !liftOK || !latencyOK {
		verdict = "NO-GO (keep `LEMON_FF_SEMANTIC` off)"
	}

	b.WriteString("## recommendation\n\n")
	fmt.Fprintf(b, "- pass@3 lift: **%+.0f pp** (threshold ≥ %.0f pp) → %s\n",
		liftPP, materialLiftPP, okNo(liftOK))
	fmt.Fprintf(b, "- ON-arm engine p95: **%dms** (budget ≤ %dms) → %s\n", onP95, engineP95Budget, okNo(latencyOK))
	fmt.Fprintf(b, "- regressions: **%d**\n\n", regressed)
	fmt.Fprintf(b, "**Verdict: %s.**\n", verdict)
}

func mark(pass bool) string {
	if pass {
		return "✅"
	}
	return "❌"
}

func okNo(ok bool) string {
	if ok {
		return "OK"
	}
	return "FAIL"
}
